<html><head>
<META http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--SafClassName="docSection1Title"--><!--SafTocEntry="1.6 Take Care of Error Handling with Bound Controls"-->
<link rel="STYLESHEET" type="text/css" href="FILES/style.css">
<link rel="STYLESHEET" type="text/css" href="FILES/docsafari.css">
<style type="text/css">	.tt1    {font-size: 10pt;}</style>
</head>
<body><H3 class="docSection1Title">1.6 Take Care of Error Handling with Bound Controls</H3>
<P>When dealing with database tasks, you are going to get runtime errors. In .NET, we call the various types of errors you can get <span class="docEmphasis">exceptions</span>. This How-To shows examples of what exceptions could occur and how to handle them using the <TT>Try</TT>, <TT>Catch</TT>, and <TT>Finally</TT> statements.</P>
<P>Adding and deleting records is fine, but what happens if an error occurs? You tried to delete an existing company, and got the screen that appears in Figure 1.10.</P>
<CENTER><H5 class="docFigureTitle">Figure 1.10. This is an unhandled error, called an exception in .NET.</H5><p><IMG BORDER="0" WIDTH="444" HEIGHT="189" src="FILES/01fig10.jpg" ALT="graphics/01fig10.jpg"></p>
</CENTER>
<P>How do you make it so errors are handled gracefully within the application using bound controls?</P>
<H4 class="docSection2Title"> Technique</H4>
<P>Error handling is one of the most important aspects of working with data, between when a user is entering data and updating the server. If you don't have proper error handling, your system will, in the best situation, give an ugly error message, and in the worst, blow up and put bad data in your system. In Visual Studio .NET, errors are classes called exceptions. Many different (inherited) types of exceptions exist.</P>
<P>Run-time exceptions can occur in just about any part of your application. They can be handled by using <TT>Try</TT>...<TT>Catch</TT>...<TT>Finally</TT> or they can be unhandled, where you will see the error in Figure 1.11.</P>
<CENTER><H5 class="docFigureTitle">Figure 1.11. This error was thrown up from one subroutine to the one that called it.</H5><p><IMG BORDER="0" WIDTH="498" HEIGHT="113" src="FILES/01fig11.jpg" ALT="graphics/01fig11.jpg"></p>
</CENTER>
<P>Take a look at a common way to trap exceptions shown in Listing 1.15.</P>
<H5 class="docExampleTitle">Listing 1.15 Standard Code for Handling Exceptions</H5>
<PRE>
Private Sub MySub()

    Try

        '-Code to be handled here

    Catch dataException as Exception

        MessageBox.Show(dataException.Message)

    Finally

        '-Code that will occur regardless of if an error occurs.

    End Try

End Sub
</PRE>
<P>Following are some basic points to help you when working with exceptions and <TT>Try...Catch...Finally</TT> blocks:</P>
<UL>
<LI><P>The name of the exception object can be whatever you want it to be. dataException was just used as an example.</P></LI>
<LI><P>Specific types of exceptions inherit from the base class of <TT>System.Exception</TT>. <TT>OleDbException</TT> is one of those classes, and you will see an example of using this class in the following steps.</P></LI>
<LI><P>You can use the <TT>Throw</TT> statement within a <TT>Catch</TT> statement to throw the exception back up to a calling subroutine.</P></LI>
<LI><P>You can use the <TT>When</TT> clause on the <TT>Catch</TT> statement to trap for specific exceptions.</P></LI>
<LI><P>When multiple <TT>Catch</TT> statements are used, each one is executed unless an <TT>End Try</TT> or <TT>End Sub</TT> is placed within a <TT>Catch</TT> block, as in this How-To.</P></LI>
<LI><P>You can use multiple <TT>Catch</TT> statements to handle various possible exceptions that can occur.</P></LI>
</UL>
<P>You will see an example of these bullets in the following steps.</P>
<H4 class="docSection2Title"> Steps</H4>
<P>Taking the form with which you have been working, you are going to modify it to trap exceptions when the record is being saved (either for additions or editing) and when the record is deleted. You will also add some code in the event when closing the form.</P>



<span style="font-weight:bold"><OL class="docList" START="1">
<LI><span style="font-weight:normal" value="1"><P>Modify the code in the <TT>Click</TT> event of the command button called btnSave. You will surround the <TT>SaveRecord</TT> routine call with a <TT>Try...Catch...End Try</TT> block. If an exception occurs, the Show method of the <TT>MessageBox</TT> class is called, passing the <TT>Message</TT> property of the Exception object called <TT>saveException</TT>. Next, the subroutine is exited. If no errors occur, then life goes on, and so does the subroutine.</P>
<H5 class="docExampleTitle">Listing 1.16 <TT>frmHowTo1_6.vb</TT>: Code Added to <TT>btnSave Click</TT> Event to Trap Save Exceptions</H5>
<PRE>
Private Sub btnSave_Click(ByVal sender As System.Object, _
                     ByVal e As System.EventArgs) Handles btnSave.Click

      Try

         '- Save the information
         SaveRecord()

      Catch saveException As Exception

         MessageBox.Show("The following error has occurred: " &amp; _
saveException.Message, "Error Saving Record")
         Exit Sub

      End Try

      '- Disable the text boxes
      ActivateEditing(False)

      If mbAddNew Then
         LoadList()
         RefreshIndividual()
         mbAddNew = False
      End If

   End Sub
</PRE></span></LI><LI><span style="font-weight:normal" value="2"><P>Modify the <TT>SaveRecord</TT> routine to "throw" the exception up to the <TT>btnSave_Click</TT> subroutine, or whatever happens to have called the <TT>SaveRecord</TT> routine. Following is the <TT>SaveRecord</TT> subroutine with the new <TT>Try...Catch...End Try</TT> block added, along with the <TT>Throw</TT> statement.</P>
<H5 class="docExampleTitle">Listing 1.17 <TT>frmHowTo1_6.vb</TT>: Pass the Exception Back Up to the Calling Routine</H5>
<PRE>
Private Sub SaveRecord()

      Try

         '- Use the BindingContext class to end the current editing so
        '  that we can update the server.
         Me.BindingContext(Me.dsCustomerIndividual, _
            "Customers").EndCurrentEdit()

         '- Perform the requested task at the dataset
         '   level using the data adapter
         odaCustomerIndividual.Update(dsCustomerIndividual, "Customers")

         '- By accepting the changes, the data gets sent back to the server
         dsCustomerIndividual.AcceptChanges()

      Catch saveException As Exception

         Throw saveException

      End Try

   End Sub
</PRE></span></LI><LI><span style="font-weight:normal" value="3"><P>Now it's time to deal with adding exception handling to the <TT>btnDelete Click</TT> event, as seen next. The <TT>Try</TT> statement is used to wrap the code that performs deletion of the data. The code then uses a <TT>Catch</TT> statement to check whether the exception that occurs is a specific <TT>OleDbException</TT>, 3621, which is an error having to do with trying to delete a record when related records exist in another table. Note that you could-and in fact should-assign this to a constant value. Because <TT>delException</TT> has been caught as an <TT>OleDbException</TT>, you can look at the <TT>NativeError</TT> property of the first error in the Errors collection to get the actual <TT>OleDb</TT> error number. If the error is not <TT>3621</TT>, then the exception is trapped with the next <TT>Catch</TT> statement, and a <TT>messagebox</TT> is displayed. If errors occur, then the subroutine is exited before the final lines of code are executed.</P>
<H5 class="docExampleTitle">Listing 1.18 <TT>frmHowTo1_6.vb</TT>: Catching Exceptions When You're Deleting a Record</H5>
<PRE>
Private Sub btnDelete_Click(ByVal sender As System.Object,
ByVal e As System.EventArgs) Handles btnDelete.Click

Try
         '- Mark the row for deletion using the RemoveAt
        ' method of the BindingContext
         Me.BindingContext(Me.dsCustomerIndividual,
"Customers").RemoveAt(Me.BindingContext(Me.dsCustomerIndividual,
"Customers").Position)

         '- Perform the requested task at the dataset
         '   level using the data adapter
         odaCustomerIndividual.Update(dsCustomerIndividual, "Customers")

         '- By accepting the changes, the data gets sent back to the server
         dsCustomerIndividual.AcceptChanges()

      Catch delException As System.Data.OleDb.OleDbException _
                           When delException.Errors(0).NativeError = 3621

         MessageBox.Show("An error occurred because of related order records.",
"Error Deleting Customer", _
               MessageBoxButtons.OK, MessageBoxIcon.Exclamation)
         Exit Sub

      Catch delException As Exception

         MessageBox.Show(delException.Message, "Error Deleting Customer",
               MessageBoxButtons.OK, MessageBoxIcon.Exclamation)

         Exit Sub

      End Try

      '- Reload the list
      LoadList()

      '- Display the first record
      RefreshIndividual()

      '- Disable the text boxes
      ActivateEditing(False)

   End Sub
</PRE></span></LI></OL></span>
<H4 class="docSection2Title"> How It Works</H4>
<P>When an exception occurs within the <TT>Try...Catch...End Try</TT> block, the <TT>Catch</TT> statements are compared when a <TT>When</TT> clause is used or when the code is simply executed. If a <TT>Throw</TT> statement is used, then an execution is thrown back up a level to the <TT>Try...Catch...End</TT> Try block containing the call to the routine where the <TT>Throw</TT> statement occurred. You can see an example of this in Figure 1.11.</P>
<H4 class="docSection2Title"> Comments</H4>
<P>Microsoft has gone to great length to let you control how you handle exceptions in .NET with the various languages. You can be as creative as you need to by using the <TT>Try...Catch...End Try</TT> block with all the clauses available.</P>
<P>Exceptions bring back plenty of information so that you can create pretty slick error handling. You can use exceptions to create a centralized routine that logs errors, or even one that e-mails exception information to you from your applications.</P>
<img src="FILES/pixel.gif" width="1" height="1" border="0"><ul></ul>
</body></html>
